### ISSUE TITLE
[FEATURE] skip verifying tls on k8s api endpoints

### ISSUE THREAD

**Issue by Ultrafenrir** [istio-ecosystem/admiral#100]
Hi! 
In our installation all cluster api endpoints located behind domain with self-signed certificate.
I tried to add our CA into default system cert store inside admiral image, but it still produce errors about untrusted certificate  

**Describe the solution you'd like**
Ability to add CA into admiral cert store, and some flag like insecure-skip-tls-verify for admiral as well

P.S.
If i specify skip tls option in kubeconfig admiral returns error
"error during create of clusterID: some-cluster Error with GlobalTrafficController controller init: failed to create global traffic controller crd client: specifying a root certificates file with the insecure flag is not allowed"

**Comment by aattuluri** [comment]
@Ultrafenrir Thanks for reporting this. I was able to reproduce this. Will determine possible fix and update the thread. Let me know if you want to contribute the fix.

**Comment by aattuluri** [comment]
@Ultrafenrir After looking into this further, both requirements of this enhancement can be achieved with configuration.

i) The root cert specified under `certificate-authority-data:` needs to have the complete chain if this is an intermediate CA.

ii) To skip verifying tls altogether `replace` the following line:
https://github.com/istio-ecosystem/admiral/blob/70af3fb2459102bc31e47ecb1307b2e342435dab/install/scripts/cluster-secret.sh#L40
with:
`insecure-skip-tls-verify: true`

It would be great if you can submit a PR to our documentation probably under examples to add these notes after you try adding the root cert approach.

**Comment by aattuluri** [comment]
@Ultrafenrir Were you able to test it with the above fix?

**Comment by aattuluri** [comment]
@Ultrafenrir I am going to close this as I verified the solutions above. Please reopen in case.
