### ISSUE TITLE
[FEATURE] AWS EKS support

### ISSUE THREAD

**Issue by Ultrafenrir** [istio-ecosystem/admiral#101]
Hi! 
As u know, for amazon eks kubeconfig is not enough to get access to the cluster , aws credential and iam-auth binary needed as well

**Describe the solution you'd like**
Maybe it's misunderstanding , but looks like now there is no option to connect bare eks cluster to admiral using standard EKS auth scheme.

**Comment by aattuluri** [comment]
@Ultrafenrir Admiral uses kubeconfig with opaque token generated based on `admiral` service account provisioned for adding the cluster to the list of clusters being watched by admiral. Once such a kubeconfig is created (using the amazon eks kubeconfig downloaded) that will be created as a secret for admiral to watch and use. So I think we should be good. We have automated that process to create such a secret (when a new cluster is created) and push it to a central cluster where admiral is running.

**Comment by Ultrafenrir** [comment]
Thanks for explanation!
