### ISSUE TITLE
[BUG] curl: (6) Could not resolve for sample application

### ISSUE THREAD

**Issue by ragunathan23** [istio-ecosystem/admiral#105]
**Describe the bug**
After deploying the sample service in the cluster and running the command 
"kubectl exec --namespace=sample -it $(kubectl get pod -l "app=webapp" --namespace=sample -o jsonpath='{.items[0].metadata.name}') -c webapp -- curl -v http://default.greeting.global" throws following error:
curl: (6) Could not resolve host: default.greeting.global
**Steps To Reproduce**
k8 cluster running in AWS with ISTIO version 1.5.2. Installed admiral and followed the steps till installing the sample app and ran the above command.
**Expected behavior**
The deployed sample app should be resolved by admiral.

Unable to proceed further with multi-cluster deployment as the above steps are not resolving the sample app. Any help much appreciated!

**Comment by kenakamu** [comment]
i had the same issue before (even though with AKS)
I miss configured core-dns to resolve global. Did you update your coredns (or kubedns) to resolve global to forward to istio core dns?

**Comment by ragunathan23** [comment]
> i had the same issue before (even though with AKS)
> I miss configured core-dns to resolve global. Did you update your coredns (or kubedns) to resolve global to forward to istio core dns?

@kenakamu I could see both coredns and kubedns configmap available in kube-system namespace. Should i remove the kubedns configmap?

**Comment by kenakamu** [comment]
not sure in AWS but in AKS we update coredns-custom to update stub domain. 
https://docs.microsoft.com/en-us/azure/aks/coredns-custom#stub-domains
You should have the same for AWS

**Comment by ragunathan23** [comment]
I could see following logs in kube-dns
- Updated stubDomains to map[global:[$(kubectl get svc -n istio-system istiocoredns -o jsonpath={.spec.clusterIP})]] 
- Invalid configuration: invalid nameserver: "$(kubectl get svc -n istio-system istiocoredns -o jsonpath={.spec.clusterIP})" (value was &TypeMeta{Kind:,APIVersion:,}), ignoring update

**Comment by ragunathan23** [comment]
> not sure in AWS but in AKS we update coredns-custom to update stub domain.
> https://docs.microsoft.com/en-us/azure/aks/coredns-custom#stub-domains
> You should have the same for AWS
@kenakamu I could see following logs in kube-dns
- Updated stubDomains to map[global:[$(kubectl get svc -n istio-system istiocoredns -o jsonpath={.spec.clusterIP})]] 
- Invalid configuration: invalid nameserver: "$(kubectl get svc -n istio-system istiocoredns -o jsonpath={.spec.clusterIP})" (value was &TypeMeta{Kind:,APIVersion:,}), ignoring update

**Comment by kenakamu** [comment]
I don't know about AWS stuff, sorry. Let's wait if others can help

**Comment by ragunathan23** [comment]
> I don't know about AWS stuff, sorry. Let's wait if others can help

@kenakamu made kubedns point to istiocoredns, but istiocoreddns throws following error. It's unable to resolve the global domain.
ERROR:
greeting.sample.svc.cluster.local.sample.global.    IN     A                                                                                       │
│ 020-05-18T13:26:26.233757Z    info    Query A record: greeting.sample.svc.cluster.local.sample.global.->{greeting.sample.svc.cluster.local.sample. │
│ 020-05-18T13:26:26.233771Z    info    Could not find the service requested

This results in 503 service unavailable in ISTIO envoy proxy.
Any idea?

**Comment by kenakamu** [comment]
The address looks wired. Did you remove the envoy filter when install admiral which example page explains

**Comment by ragunathan23** [comment]
> The address looks wired. Did you remove the envoy filter when install admiral which example page explains

@kenakamu yes I did remove the envoy filter. I am not sure what configuration makes this weird dns entry. There is one Destonationrule for istio-multicluster-ingressgateway with *.global entry for the host. Not sure whether this has any impact. With ISTIO things are made so complex.

**Comment by kenakamu** [comment]
What is ServiceEntry looks like now? Does default.greeting.global points to greeting.sample.svc.cluster.local?

**Comment by ragunathan23** [comment]
> What is ServiceEntry looks like now? Does default.greeting.global points to greeting.sample.svc.cluster.local?

@kenakamu please find the service entry for greeting, it does point to local fqdn.

` apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: "2020-05-18T06:53:54Z"
  generation: 1
  labels:
    identity: greeting
  name: default.greeting.global-se
  namespace: admiral-sync
  resourceVersion: "20802297"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/admiral-sync/serviceentries/default.greeting.global-se
  uid: 56f7a764-98d4-11ea-b5cb-0265f8cc5958
spec:
  addresses:
  - 240.0.10.1
  endpoints:
  - address: greeting.sample.svc.cluster.local
    locality: ap-south-1
    ports:
      http: 80
  hosts:
  - default.greeting.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: DNS `

**Comment by kenakamu** [comment]
yeah it does looks right. so something went wrong when doing the local lookup. If you curl to http://greeting.sample.svc.cluster.local, I assume its working as expected? 

By the way, when I had the issue before, to avoid the complex troubleshooting, I simply remove istio and admiral and reinstall everything as it won't take much time anyway. 

If you look into coredns or coredns-custom, whatever AWS uses, do you see global domain is resolved by correct istiocoredns?

**Comment by ragunathan23** [comment]
I am not using kubedns and not coredns. Do we need coredns for this to
work. As I could see kubedns indeed forwards request to istiocoredns and
the call reaches the respective pod but returns 503.

**Comment by kenakamu** [comment]
I mean it comes with k8s and AKS uses coredns. I dont know if AWS uses coredns or kubedns. It doesn't matter but you simply need to let k8s dns to forward any name end with global to be resolved by istio core dns. So if you see the name resolution is actually forwarded to istio dns, then that part should be fine. The interesting part is that istio dns didnt solve it right. Did you also make sure that you register global domain to be resolved as part of istio install?

```yaml
values:
    global:
      # Provides dns resolution for global services
      podDNSSearchNamespaces:
        - global
        - "{{ valueOrDefault .DeploymentMeta.Namespace \"default\" }}.global"
```

**Comment by ragunathan23** [comment]
No I didn't do this step. Is that the problem?

**Comment by kenakamu** [comment]
That is not the step but it is part of the install yaml from istio multi cluster.

https://istio.io/docs/setup/install/multicluster/gateways/

**Comment by ragunathan23** [comment]
Sorry I couldn't find this step.

**Comment by kenakamu** [comment]
the install step is like below

Install Istio:
```
$ istioctl manifest apply \
    -f install/kubernetes/operator/examples/multicluster/values-istio-multicluster-gateways.yaml
```
And the values-istio-multicluster-gateways.yaml should contains it. I dont know which template you use to install but this is the step I follow to install istio to multi cluster

**Comment by ragunathan23** [comment]
I did this step for demo profile not the default profile.

**Comment by kenakamu** [comment]
try follow the steps in https://istio.io/docs/setup/install/multicluster/gateways/

**Comment by ragunathan23** [comment]
I did follow deploy application and setting up dns from above doc. After
that followed admiral configuration. This what admiral recommend as well.

**Comment by kenakamu** [comment]
Then I have no other idea. What I did was to create AKS clusters and follow the doc to install itsio to both clusters. Update DNS and confirm the demo app from istio works anyway before install admiral.

Once I failed to setup coredns domain to solve *.global* rather than *global* and also added port number at the end of forward IP which I didnt need. Once I solved it, everything else just worked.

**Comment by ragunathan23** [comment]
May be I will try this. But the curl request does reach the greeting app,
which I could see from Istio proxy log. But not sure why it's returning
503. Is there anyone from admiral could help.

**Comment by aattuluri** [comment]
@ragunathan23 Ok, it would be good if you can uninstall istio and reinstall it using the steps [here](https://istio.io/docs/setup/install/multicluster/gateways/#deploy-the-istio-control-plane-in-each-cluster) and then follow admiral steps. The `demo` profile doesn't have the multicluster configurations.

Like @kenakamu suggested, I would first try making the call `http://greeting.sample.svc.cluster.local` to make sure everything works and then test `http://default.greeting.global`

Also, please share the coredns config map after you set it up to resolve `global` entries.

**Comment by ragunathan23** [comment]
> @ragunathan23 Ok, it would be good if you can uninstall istio and reinstall it using the steps [here](https://istio.io/docs/setup/install/multicluster/gateways/#deploy-the-istio-control-plane-in-each-cluster) and then follow admiral steps. The `demo` profile doesn't have the multicluster configurations.
> 
> Like @kenakamu suggested, I would first try making the call `http://greeting.sample.svc.cluster.local` to make sure everything works and then test `http://default.greeting.global`
> 
> Also, please share the coredns config map after you set it up to resolve `global` entries.

@kenakamu @aattuluri Thanks for your response. After re-installing the call http://default.greeting.global worked and did return 200. 
NOTE: This time created ISTIO with default profile and not demo.

When I ran the curl request multiple times, the request gets served from cluster 1, and none of them served from cluster 2. My clusters are running in same region. Is this the reason for this behavior?

**Comment by kenakamu** [comment]
I see the same behavior in my setup as well and I believe it comes from locality settings in Istio. You ca n create Global Traffic Policy in Cluster 1 to set weight 50:50 to both cluster for load balancing

**Comment by aattuluri** [comment]
@ragunathan23 If both clusters belong to the same region then yes, the request should load balance between the two. Can you share the generated ServiceEntry or check if it has both cluster local and remote endpoints?
@kenakamu GTP works if regions are different, in his case both clusters are in the same region.

**Comment by ragunathan23** [comment]
> @ragunathan23 If both clusters belong to the same region then yes, the request should load balance between the two. Can you share the generated ServiceEntry or check if it has both cluster local and remote endpoints?
> @kenakamu GTP works if regions are different, in his case both clusters are in the same region.

@aattuluri please find the service entry. I could see both local and remote endpoint configured.

apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  creationTimestamp: "2020-05-19T01:50:40Z"
  generation: 46
  labels:
    identity: greeting
  name: default.greeting.global-se
  namespace: admiral-sync
  resourceVersion: "20975065"
  selfLink: /apis/networking.istio.io/v1beta1/namespaces/admiral-sync/serviceentries/default.greeting.global-se
  uid: 24f8c4f2-9973-11ea-b5cb-0265f8cc5958
spec:
  addresses:
  - 240.0.10.1
  endpoints:
  - address: greeting.sample.svc.cluster.local
    locality: ap-south-1
    ports:
      http: 80
  - address: a548c8d17997111ea9f86024279d20ed-815069357.ap-south-1.elb.amazonaws.com
    locality: ap-south-1
    ports:
      http: 15443
  hosts:
  - default.greeting.global
  location: MESH_INTERNAL
  ports:
  - name: http
    number: 80
    protocol: http
  resolution: DNS

**Comment by ragunathan23** [comment]
> > @ragunathan23 If both clusters belong to the same region then yes, the request should load balance between the two. Can you share the generated ServiceEntry or check if it has both cluster local and remote endpoints?
> > @kenakamu GTP works if regions are different, in his case both clusters are in the same region.
> 
> @aattuluri please find the service entry. I could see both local and remote endpoint configured.
> 
> apiVersion: networking.istio.io/v1beta1
> kind: ServiceEntry
> metadata:
> creationTimestamp: "2020-05-19T01:50:40Z"
> generation: 46
> labels:
> identity: greeting
> name: default.greeting.global-se
> namespace: admiral-sync
> resourceVersion: "20975065"
> selfLink: /apis/networking.istio.io/v1beta1/namespaces/admiral-sync/serviceentries/default.greeting.global-se
> uid: 24f8c4f2-9973-11ea-b5cb-0265f8cc5958
> spec:
> addresses:
> 
> * 240.0.10.1
>   endpoints:
> * address: greeting.sample.svc.cluster.local
>   locality: ap-south-1
>   ports:
>   http: 80
> * address: xxxxxxxxxxx.ap-south-1.elb.amazonaws.com
>   locality: ap-south-1
>   ports:
>   http: 15443
>   hosts:
> * default.greeting.global
>   location: MESH_INTERNAL
>   ports:
> * name: http
>   number: 80
>   protocol: http
>   resolution: DNS

@aattuluri when I continuously excute the call, it does load balance and for the multiple clusters within the same region. One more question does admiral work with the ISTIO demo profile as well?

**Comment by aattuluri** [comment]
@ragunathan23 Cool. I don't think it works with `demo` profile from what I remember since it doesn't install the multi-cluster configuration.
