### ISSUE TITLE
[BUG] Admiral shouldn't log errors when installed into a cluster without Argo Rollouts

### ISSUE THREAD

**Issue by josephpeacock** [istio-ecosystem/admiral#109]
**Describe the bug**
It doesn't seem to effect functionality, but there are repeated logs of `Failed to list *v1alpha1.Rollout: the server could not find the requested resource (get rollouts.argoproj.io)` when Admiral is installed into a cluster that doesn't have Argo Rollouts. 

**Steps To Reproduce**

Follow the demoSingleCluster example in a cluster that lacks the rollouts CRD.

**Expected behavior**
Admiral shouldn't log errors when argo rollouts aren't present in a cluster.

**Comment by pnovotnak** [comment]
Is anyone working on this? I'm happy to take it on

**Comment by aattuluri** [comment]
@pnovotnak not at the moment, assigned it to you

**Comment by aattuluri** [comment]
Fixed with https://github.com/istio-ecosystem/admiral/pull/119
