### ISSUE TITLE
[BUG] Service entry needs to be cleaned up after annotation update

### ISSUE THREAD

**Issue by vrushalijoshi** [istio-ecosystem/admiral#125]
**Describe the bug**
When a admiral ignores a service which was previously synced, service entry does not get updated in admiral-sync namespace.

**Steps To Reproduce**
Pick a service which is currently not ignored by admiral (admiral.io/ignorea annotation is false). Update the annotation to be true, admiral now will not sync this service, but corresponding service entry does not get updated in admiral-sync namespace

**Expected behavior**
Update to deployment annotation should update the service entry accordingly

**Comment by aattuluri** [comment]
Fixed with https://github.com/istio-ecosystem/admiral/pull/126
