### ISSUE TITLE
[BUG] Route to the in-cluster service/pod by default

### ISSUE THREAD

**Issue by josephpeacock** [istio-ecosystem/admiral#127]
**Describe the bug**
If there are multiple deployments running, in multiple clusters, with the same Identity, in the same locality, Admiral currently creates a service entry with endpoints pointing to every single one. This weights the cross-cluster calls equally to the in-cluster calls.

**Steps To Reproduce**
Spin up two clusters in the same AWS region and deploy the same app into both. Examine the service entry, and you'll see one endpoint pointing to *.svc.cluster.local, and one to the ingress-gateway load balancer DNS name.

**Expected behavior**
If a destination is present in the same cluster as the source, Admiral's default behavior should be to always route the request to the local destination, regardless of other possible destinations with the same identity.

Possibly related to https://github.com/istio-ecosystem/admiral/issues/62

**Comment by wenxian** [comment]
My experience with installing Istio 1.6 [replica control plane](https://istio.io/latest/docs/setup/install/multicluster/gateways/), it always goes to the local one as the locality is enabled by default. Unless it's detected outlier, then it will failover to other endpoints

**Comment by benchi** [comment]
Look into solving this with the EW Gateway type.

**Comment by aattuluri** [comment]
This should be resolved with east west gateway with istio 1.8 and above.
