### ISSUE TITLE
Admiral Cache 

### ISSUE THREAD

**Issue by wenxian** [istio-ecosystem/admiral#135]
Don't know how long the admiral cache exist.

First Time:
Repository: a admiral-demo in us-east-1 (web & greeting) and us-west-2 (web)
Observe: the greeting SE in us-west-2 only created after a Dependency is declared.

Then:
Removing all Dependency and admiral-demo namespace in both us-east-1 and us-west-2. Deploy again the same thing - admiral-demo in us-east-1 (web & greeting) and us-west-2 (web)
Observe:  the greeting SE in us-west-2 is created without Dependency

Not sure if this is expected or a bug

**Comment by aattuluri** [comment]
@wenxian SEs are created only if there are dependencies declared, there is an issue open for creating SEs in all clusters without dependency.
This is a [bug](https://github.com/istio-ecosystem/admiral/blob/9e3a12241626bf29e08f9391ef8d4dc5c85f1848/admiral/pkg/clusters/types.go#L264) if admiral wasn't restarted as `Delete` dependency is not implemented.

**Comment by aattuluri** [comment]
We think this should be fixed with https://github.com/istio-ecosystem/admiral/issues/9 and its currently targeted for v1.1
