### ISSUE TITLE
Following global traffic policy example results in unresolved dns records [BUG]

### ISSUE THREAD

**Issue by yaron-idan** [istio-ecosystem/admiral#161]
**Describe the bug**
Not sure if this is a bug actually. I'm trying to follow the example described [here](https://github.com/istio-ecosystem/admiral/blob/master/docs/Architecture.md#global-traffic-policy) but after creating the GlobalTrafficPolicy pods can't resolve to either `west.greeting.global` or `east.greeting.global`. 
This makes sense because I haven't created anything to instruct these records to be created, but I'm not sure what actions are required to achieve that.

**Steps To Reproduce**
Create 2 EKS clusters in us-east-1 and us-east-2 regions
Install istio-1.7.6 multicluster on 2 clusters according to this [guide](https://istio.io/v1.7/docs/setup/install/multicluster/gateways/)
Install admiral on both clusters following this [guide](https://github.com/istio-ecosystem/admiral/blob/master/docs/Examples.md)

**Expected behavior**
The failover global traffic policy should be able to route traffic to `east.greeting.global` locally within us-east-1 cluster, and automatically failover to us-east-2 cluster once health is degraded.

**Comment by aattuluri** [comment]
@yaron-idan This is a feature gap and being worked on https://github.com/istio-ecosystem/admiral/pull/162. Should be available later this week.

**Comment by yaron-idan** [comment]
Thanks @aattuluri , those are great news!
