### ISSUE TITLE
[BUG] Http Demo for Remote cluster doesn't work due to missing annotation

### ISSUE THREAD

**Issue by PavelKarpenka** [istio-ecosystem/admiral#163]
Hello!
When I'm reproducing Multicluster setup from [here](https://github.com/istio-ecosystem/admiral/blob/master/docs/Examples.md), Admiral creates `default.greeting.global-se` ServiceEntry for remote cluster instead of `stage.greeting.global-se`.
So `admiral-sync` namespace contents in Cluster 1 look like:
```
NAME                          HOSTS                        LOCATION        RESOLUTION   AGE
default.greeting.global-se    [default.greeting.global]    MESH_INTERNAL   DNS          76m
stage.greeting.global-se      [stage.greeting.global]      MESH_INTERNAL   DNS          107m
stage.grpc-server.global-se   [stage.grpc-server.global]   MESH_INTERNAL   DNS          106m
stage.webapp.global-se        [stage.webapp.global]        MESH_INTERNAL   DNS          107m
```

And because of that, ServiceEntry for `greeting` service in Cluster 1 doesn't have second endpoint and `Http Demo` command sends traffic only to local cluster.

This happens because this file `yaml/remotecluster_sample.yaml` doesn't have annotation `admiral.io/env: stage` in `greeting` deployment.
When I added the annotation, http demo was fixed.

Please take care and thank you for Admiral!

Pavel

**Comment by aattuluri** [comment]
@PavelKarpenka Thanks for reporting it, I will be fixing it as part of my current PR https://github.com/istio-ecosystem/admiral/pull/162
