### ISSUE TITLE
[BUG] CRDs are broken in 1.24.x

### ISSUE THREAD

**Issue by tibers** [istio-ecosystem/admiral#287]
**Describe the bug**
CRDs are broken in k8s version 1.24.x

**Steps To Reproduce**
Attempt to install admiral. At the step `$ADMIRAL_HOME/scripts/install_admiral.sh $ADMIRAL_HOME`, the installation will fail with `error: resource mapping not found for name: "globaltrafficpolicies.admiral.io" namespace: "" from "/Users/tibers/Downloads/admiral-install-v1.2/yaml/remotecluster.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"`. This is because CRDs are now `apiextensions.k8s.io/v1`.

**Expected behavior**
It just works.

Fixing that leads to:
```
error: error validating "/Users/tibers/Downloads/admiral-install-v1.2/yaml/remotecluster.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): missing required field "versions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false
namespace/admiral unchanged
error: error validating "/Users/tibers/Downloads/admiral-install-v1.2/yaml/demosinglecluster.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): missing required field "versions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]; if you choose to ignore these errors, turn validation off with --validate=false
```

It's extremely likely the whole project needs to be freshened up.

Related: https://github.com/istio-ecosystem/admiral/issues/264

**Comment by ku9nov** [comment]
Hey @aattuluri 
A [pull request](https://github.com/istio-ecosystem/admiral/pull/262/files) was merged to support Kubernetes version 1.22, but after that, you did not create a new release and did not update this [documentation](https://github.com/istio-ecosystem/admiral/blob/master/docs/Examples.md), making it impossible to install Admiral based on this documentation. I think it's a main problem.

**Comment by nirvanagit** [comment]
@ku9nov: the readme has been updated, can you please try now?
@tibers: can you please retry now.

We recently pushed a lot of pending changes to upstream.
Please let me know.

**Comment by ku9nov** [comment]
Hello @nirvanagit, Unfortunately, it was a long time ago, and I don't remember exactly how I encountered this problem, but I do know that we ultimately do not use Admiral for this cluster, and all the functionality was configured using Istio, which is fully sufficient for our needs. Thank you.

**Comment by aattuluri** [comment]
Validated with k8s 1.28 and everything works.
