### ISSUE TITLE
Dead readme.md presentation link

### ISSUE THREAD

**Issue by moncefunity** [istio-ecosystem/admiral#291]
This link in the readme seems to be dead

[Admiral – Enabling Multi-Cluster Mesh](https://www.meetup.com/San-Diego-Cloud-Native-Computing-Meetup/events/262826967/)

**Comment by aaminaa01** [comment]
The link is opening a login page for meetup.com. Should there be something else there instead? Could you please explain the issue in a little more detail?
TIA!

**Comment by aattuluri** [comment]
Closed with https://github.com/istio-ecosystem/admiral/pull/292
