### ISSUE TITLE
Automate admiral releases for new tags

### ISSUE THREAD

**Issue by aattuluri** [istio-ecosystem/admiral#30]
Currently, creating tags isn't triggering a release build in circle ci.

We need `Makefile` to do the following when a `new_tag` is created:

i) Publish an image whenever a new tag (say `new_tag`) is created
ii) Package an artifact with the output of `make gen-yaml` into `admiral-install-{new_tag}.tar.gz`
iii) Create a release with the name `new_tag` and attach artifact from ii) to this release

**Comment by sterchelen** [comment]
@aattuluri I would like to work on it.

**Comment by aattuluri** [comment]
@sterchelen Please go for it

**Comment by aattuluri** [comment]
@sterchelen 
Do you want to take a look?
https://circleci.com/gh/istio-ecosystem/admiral/55?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification

**Comment by sterchelen** [comment]
Yes I will

**Comment by sterchelen** [comment]
It's a known issue from kustomize repo:
https://github.com/kubernetes-sigs/kustomize/issues/1680

**Comment by sterchelen** [comment]
Fix in  #38

**Comment by aattuluri** [comment]
@sterchelen https://circleci.com/gh/istio-ecosystem/admiral/58

**Comment by sterchelen** [comment]
How did you trigger this?
You must push via:
git push origin tag your-tag

**Comment by aattuluri** [comment]
I created a release from github releases page, will try pushing the tag today.

**Comment by sterchelen** [comment]
@aattuluri Did you find time to test by pushing the tag ?

**Comment by aattuluri** [comment]
Yes, I just did, same problem:
https://circleci.com/gh/istio-ecosystem/admiral/60

```
git push origin tag test-release
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 164 bytes | 164.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To github.com:istio-ecosystem/admiral.git
 * [new tag]         test-release -> test-release
```

**Comment by sterchelen** [comment]
Ok, I will test it tonight

**Comment by aattuluri** [comment]
Sounds good

**Comment by sterchelen** [comment]
I tested again on my circleci without issue !
Checkout the link https://circleci.com/gh/sterchelen/admiral/73
If you can connect you to the remote job while it is processing and check the ENV variables use by the `ghr` cli

**Comment by aattuluri** [comment]
@sterchelen Let me test it, will get back to you.

**Comment by aattuluri** [comment]
I had to add the `GITHUB_TOKEN` in circleci. It works!
