### ISSUE TITLE
Switch from vendor to go modules

### ISSUE THREAD

**Issue by aattuluri** [istio-ecosystem/admiral#32]
Currently, admiral project uses `vendor` for its dependencies. Switch to go modules for better dependency management.

**Comment by vdepatla** [comment]
I can take on this one ..

**Comment by aattuluri** [comment]
@vdepatla Sounds good. I will look forward for a PR.

**Comment by nickborysov** [comment]
@aattuluri https://github.com/istio-ecosystem/admiral/pull/36

**Comment by aattuluri** [comment]
@vdepatla https://github.com/istio-ecosystem/admiral/pull/36 looks good to me. I will go ahead and merge this, let me know if you think otherwise.

**Comment by vdepatla** [comment]
sure Thanks

**Comment by aattuluri** [comment]
Solved with https://github.com/istio-ecosystem/admiral/pull/36
