### ISSUE TITLE
[BUG] Image is not pushed to docker hub for tags/releases

### ISSUE THREAD

**Issue by aattuluri** [istio-ecosystem/admiral#40]
**Describe the bug**
The docker image for admiral is not pushed for release/tag builds

**Steps To Reproduce**
Create a tag/release and see that the docker hub doesn't have the image with this new tag

**Expected behavior**
Should see the new tag (release) in docker hub.

**Comment by anusha5695** [comment]
Hi @aattuluri : Can i pick this?

**Comment by aattuluri** [comment]
@anusha5695 yes

**Comment by aattuluri** [comment]
@anusha5695 Still working on this?

**Comment by aattuluri** [comment]
Fixed with PR commit https://github.com/istio-ecosystem/admiral/pull/61
