### ISSUE TITLE
[FEATURE] Add integration tests for admiral

### ISSUE THREAD

**Issue by aattuluri** [istio-ecosystem/admiral#66]
**Is your feature request related to a problem? Please describe.**
Admiral should have integration tests to cover the following scenarios:
i) K8s version + Istio version
ii) Multi cluster examples

**Comment by Mengying-Li** [comment]
Done and merged to master

**Comment by aattuluri** [comment]
I think the multi-cluster examples are not covered with this issue, we will address it as another issue.
