### ISSUE TITLE
[FEATURE] DOCS: Documentation site

### ISSUE THREAD

**Issue by saradhis** [istio-ecosystem/admiral#72]
**Is your feature request related to a problem? Please describe.**
Docs are mostly in the README. It would be good to separate the documentation for easy access and organization.

**Describe the solution you'd like**
Documentation similar to https://argoproj.github.io/argo-cd/ would be good. This could also host the Admiral API documentation.

**Comment by aattuluri** [comment]
Duplicate of https://github.com/istio-ecosystem/admiral/issues/60
