### ISSUE TITLE
[BUG] Infer ServiceEntry ports from destination service

### ISSUE THREAD

**Issue by josephpeacock** [istio-ecosystem/admiral#76]
The serviceEntry should add ports based on those present in the service it will be pointing to. Currently it is hardcoded to default http ports (and named http).

Thanks to Martin Baillie for the report!

> for those at Intuit more familiar with the code, I was thinking these lines should not be hardcoded and should instead be inferred from the respective Service  ports and port names?
https://github.com/istio-ecosystem/admiral/blob/master/admiral/pkg/clusters/serviceentry.go#L84-L85
since my Service ports are named grpc I am being bitten by: https://istio.io/docs/reference/config/networking/service-entry/#ServiceEntry-Endpoint

**Comment by aattuluri** [comment]
Fixed with https://github.com/istio-ecosystem/admiral/pull/148
