### ISSUE TITLE
[FEATURE] Create/Update Istio Sidecar resource in workload namespace based on its dependencies

### ISSUE THREAD

**Issue by vrushalijoshi** [istio-ecosystem/admiral#83]
**Is your feature request related to a problem? Please describe.**
Sidecar resource needs to be created/updated in workload's namespace based on its defined dependencies. This will be useful to limit amount of configuration pushed out to the envoy sidecar instances within mesh.

**Comment by aattuluri** [comment]
Fixed with https://github.com/istio-ecosystem/admiral/pull/84
