### ISSUE TITLE
Delete doesn't clean up ServiceEntries

### ISSUE THREAD

**Issue by jwebb49** [istio-ecosystem/admiral#9]
deleting deployments doesn't clean up service entries that are created in the admiral-sync namespace.

**Comment by martinbaillie** [comment]
I've been evaluating Admiral and also noticed this. I feel cleanup is quite a fundamental feature and I'm wondering if anyone is looking at it?

**Comment by aattuluri** [comment]
@martinbaillie Agreed, there isn't anyone looking at it right now. We can add this to milestone v0.1.

**Comment by Ultrafenrir** [comment]
+1

**Comment by pisto** [comment]
eyeing this
