### ISSUE TITLE
[BUG] Admiral crashes on GTP add followed by delete operation

### ISSUE THREAD

**Issue by asushanthk** [istio-ecosystem/admiral#90]
**Describe the bug**
Admiral crashes on GTP add followed by delete operation

**Steps To Reproduce**
1. Start with admiral + create secret for cluster so that Admiral starts monitoring the cluster.
2. Add a GTP with no matching deployment. I used the GTP yaml as is from https://github.com/istio-ecosystem/admiral/blob/master/docs/Architecture.md
3. Wait for log msg mentioning the GTP was skipped as there was no matching deployment.
4. Delete the GTP. 
5. Admiral panics and crashes

**Expected behavior**
Admiral should not crash.

**Comment by josephpeacock** [comment]
@asushanthk thanks for your report! Could you share the stacktrace from the panic?

**Comment by asushanthk** [comment]
@josephpeacock 

E0407 08:49:17.149035   80726 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x227daa0), concrete:(*runtime._type)(nil), asserted:(*runtime._type)(0x2467300), missingMethod:""} (interface conversion: interface {} is nil, not *v1.GlobalTrafficPolicy)
goroutine 121 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x22bafa0, 0xc000bf6120)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:48 +0x82
panic(0x22bafa0, 0xc000bf6120)
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1b2
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*GlobalTrafficController).Deleted(0xc0000ed090, 0x0, 0x0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/globaltraffic.go:79 +0x73
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).processItem(0xc00032cdb0, 0xc00078c480, 0x13, 0x0, 0x0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:129 +0xec
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).processNextItem(0xc00032cdb0, 0x1803800)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:104 +0x100
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).runWorker(0xc00032cdb0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:91 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000715f68)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000737f68, 0x12a05f200, 0x0, 0x1, 0xc0000a2480)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:88
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).Run(0xc00032cdb0, 0xc0000a2480)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:87 +0x311
created by github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.NewController
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:65 +0x430
E0407 08:49:17.149202   80726 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x227daa0), concrete:(*runtime._type)(nil), asserted:(*runtime._type)(0x2467300), missingMethod:""} (interface conversion: interface {} is nil, not *v1.GlobalTrafficPolicy)
goroutine 121 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x22bafa0, 0xc000bf6120)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:48 +0x82
panic(0x22bafa0, 0xc000bf6120)
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1b2
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:55 +0x105
panic(0x22bafa0, 0xc000bf6120)
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1b2
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*GlobalTrafficController).Deleted(0xc0000ed090, 0x0, 0x0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/globaltraffic.go:79 +0x73
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).processItem(0xc00032cdb0, 0xc00078c480, 0x13, 0x0, 0x0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:129 +0xec
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).processNextItem(0xc00032cdb0, 0x1803800)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:104 +0x100
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).runWorker(0xc00032cdb0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:91 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000715f68)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000737f68, 0x12a05f200, 0x0, 0x1, 0xc0000a2480)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:88
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).Run(0xc00032cdb0, 0xc0000a2480)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:87 +0x311
created by github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.NewController
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:65 +0x430
panic: interface conversion: interface {} is nil, not *v1.GlobalTrafficPolicy [recovered]
	panic: interface conversion: interface {} is nil, not *v1.GlobalTrafficPolicy [recovered]
	panic: interface conversion: interface {} is nil, not *v1.GlobalTrafficPolicy

goroutine 121 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:55 +0x105
panic(0x22bafa0, 0xc000bf6120)
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1b2
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/runtime/runtime.go:55 +0x105
panic(0x22bafa0, 0xc000bf6120)
	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:679 +0x1b2
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*GlobalTrafficController).Deleted(0xc0000ed090, 0x0, 0x0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/globaltraffic.go:79 +0x73
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).processItem(0xc00032cdb0, 0xc00078c480, 0x13, 0x0, 0x0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:129 +0xec
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).processNextItem(0xc00032cdb0, 0x1803800)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:104 +0x100
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).runWorker(0xc00032cdb0)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:91 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000715f68)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000737f68, 0x12a05f200, 0x0, 0x1, 0xc0000a2480)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/mod/k8s.io/apimachinery@v0.17.3/pkg/util/wait/wait.go:88
github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.(*Controller).Run(0xc00032cdb0, 0xc0000a2480)
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:87 +0x311
created by github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral.NewController
	/Users/sa/github.com/istio-ecosystem/admiral/admiral/pkg/controller/admiral/controller.go:65 +0x430
